[project]
name = "thinking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncio>=4.0.0",
    "mcp[cli]>=1.15.0",
    "pathspec>=0.12.1",
]
